apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-readers
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-readers
  template:
    metadata:
      labels:
        name: cluster-readers
    spec:
      serviceAccountName: cluster-readers
      containers:
        - name: cluster-readers
          # Replace this with the built image name
          image: quay.io/jharrington22/cluster-readers-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cluster-readers
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-readers"
