kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-readers
subjects:
- kind: ServiceAccount
  name: cluster-readers
roleRef:
  kind: Role
  name: cluster-readers
  apiGroup: rbac.authorization.k8s.io
